version: '3.9'
services:
  postgres:
    container_name: postgres-dev
    image: 'postgres:16.1'
    env_file:
      - ./database.dev.env
    networks:
      - backend-dev
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin-dev
    image: 'dpage/pgadmin4:7.8'
    env_file:
      - ./database.dev.env
    networks:
      - backend-dev
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'

networks:
  backend-dev:
    name: backend-dev
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
