name: One Day One Plant Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  build-image:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
      - uses: actions/cache@v4
        with:
          path: |
            apps/app-frontend/node_modules
            apps/app-backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: apps/app-backend/
          tags: |
            mozenn/micoris:odop-core-${{ steps.get_version.outputs.VERSION }}
          push: true
